PlaceImmobilizationAndCTOrder:
  entryContent: 制模定位申请
  content: 制模定位申请
  completedContent: 制模定位已申请
  workspace:
    workspaceType: DYNAMIC_FORM1111
    dynamicFormTemplate:
      - templateId: ImmoAndCTOrder
    eclipseModuleId:
ScheduleCTScan>>DoCTRecord:
  entryContent: 预约CT扫描
  content: 预约CT扫描
  completedContent: CT扫描已预约
  workspace:
    workspaceType: SCHEDULE_SINGLE
    viewDynamicFormTemplateList:
      - ImmoAndCTOrder
      - RepositionOrder
    defaultAppointmentView: WEEK
    dynamicFormTemplate:
    eclipseModuleId:
DoCTRecord:
  entryContent: CT定位扫描患者列表
  content: CT定位扫描
  completedContent: CT定位扫描已完成
  workspace:
    workspaceType: DYNAMIC_FORM
    viewDynamicFormTemplateList:
      - ImmoAndCTRecord
    dynamicFormTemplate:
      - templateId: ImmoAndCTRecord
    eclipseModuleId:
ImportCTImage:
  entryContent: 导入图像
  content: 导入图像
  completedContent: 图像已导入
  workspace:
    workspaceType: TPS
    defaultTPS: ECLIPSE
    dynamicFormTemplate:
    eclipseModuleId: VA_VD
TargetContouring:
  entryContent: 勾画靶区
  content: 勾画靶区
  completedContent: 靶区已勾画
  workspace:
    workspaceType: TPS
    defaultTPS: ECLIPSE
    dynamicFormTemplate:
    eclipseModuleId: Contouring
PlacePlanningOrder:
  entryContent: 计划申请
  content: 计划申请
  completedContent: 计划已申请
  workspace:
    workspaceType: DYNAMIC_FORM
    viewDynamicFormTemplateList:
      - PlanningOrder
    dynamicFormTemplate:
      - templateId: PlanningOrder
    eclipseModuleId:
TreatmentPlanning:
  entryContent: 制作计划
  content: 制作计划
  completedContent: 计划已完成
  workspace:
    workspaceType: TPS_DYNAMIC_FORM
    defaultTPS: ECLIPSE
    dynamicFormTemplate:
      - templateId: PlanningRecord
    eclipseModuleId: VA_VD
PlanApproval:
  entryContent: 计划审批
  content: 计划审批
  completedContent: 计划已审批
  workspace:
    workspaceType: TPS_DYNAMIC_FORM
    defaultTPS: ECLIPSE
    dynamicFormTemplate:
      - templateId: PlanningRecord
    eclipseModuleId: VA_VD
TxPreparation:
  entryContent: 治疗准备
  content: 治疗准备
  completedContent: 治疗准备已完成
  workspace:
    workspaceType: TPS
    defaultTPS: ECLIPSE
    dynamicFormTemplate:
    eclipseModuleId: TxPreparation
ScheduleTreatment>>Daily Treatment:
  entryContent: 预约治疗
  content: 预约治疗
  completedContent: 治疗已预约
  workspace:
    workspaceType: SCHEDULE_MULTIPLE
    viewDynamicFormTemplateList:
      - PlanningRecord
    defaultAppointmentView: WEEK
    dynamicFormTemplate:
    eclipseModuleId:
Daily Treatment:
  entryContent: 治疗患者列表
  content: 治疗
  completedContent: 治疗中
  needChargeBill: true
  workspace:
    workspaceType: DYNAMIC_FORM
    viewDynamicFormTemplateList:
      - PlanningRecord
    dynamicFormTemplate:
      - templateId: TreatmentRecord
    eclipseModuleId:
PlanningQA:
  entryContent: 计划验证
  content: 计划验证
  completedContent: 计划验证已完成
  workspace:
    workspaceType: DYNAMIC_FORM
    dynamicFormTemplate:
      - templateId: QARecord
    eclipseModuleId:
PlaceMRIOrder:
  entryContent: MRI定位申请
  content: MRI定位申请
  completedContent: MRI定位申请已完成
  workspace:
    workspaceType: DYNAMIC_FORM
    dynamicFormTemplate:
      - templateId: MRIOrder
    eclipseModuleId:
ScheduleMRI>>DoMRI:
  entryContent: 预约MRI扫描
  content: 预约MRI扫描
  completedContent: MRI扫描已预约
  workspace:
    workspaceType: SCHEDULE_SINGLE
    viewDynamicFormTemplateList:
      - MRIOrder
      - ImmoAndCTOrder
      - RepositionOrder
    defaultAppointmentView: WEEK
    dynamicFormTemplate:
    eclipseModuleId:
DoMRI:
  entryContent: MRI定位扫描患者列表
  content: MRI定位扫描
  completedContent: MRI定位扫描已完成
  workspace:
    workspaceType: DYNAMIC_FORM
    dynamicFormTemplate:
      - templateId: MRIRecord
    eclipseModuleId:
ImportMRIImage:
  entryContent: 导入MRI图像
  content: 导入MRI图像
  completedContent: 导入MRI图像已完成
  workspace:
    workspaceType: TPS
    defaultTPS: ECLIPSE
    dynamicFormTemplate:
    eclipseModuleId: VA_VD
PlaceRepositionOrder:
  entryContent: 再次定位申请
  content: 再次定位申请
  completedContent: 再次定位已申请
  workspace:
    workspaceType: DYNAMIC_FORM
    dynamicFormTemplate:
      - templateId: ImmoAndCTOrder
    eclipseModuleId:
